image: ghcr.io/home-assistant/{arch}-hassio-dns
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/home-assistant/plugin-dns/.*
labels:
  io.hass.type: dns
  org.opencontainers.image.title: Home Assistant DNS Plugin
  org.opencontainers.image.description: Home Assistant Supervisor plugin for DNS
  org.opencontainers.image.source: https://github.com/home-assistant/plugin-dns
  org.opencontainers.image.authors: The Home Assistant Authors
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
args:
  COREDNS_VERSION: 1.11.4
